version: "3.8"

services:
  # Base de Datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: universidad_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-universidad_sistema}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - universidad_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación Node.js
  app:
    build:
      context: ..
      dockerfile: docker/node/Dockerfile
    container_name: universidad_app
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-universidad_sistema}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ../src:/app/src
      - ../package.json:/app/package.json
      - node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - universidad_network
    command: npm run dev

  # Adminer para administración de BD (opcional)
  adminer:
    image: adminer:latest
    container_name: universidad_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - universidad_network

  # pgAdmin para administración de BD (alternativa)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: universidad_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@universidad.edu.gt
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - universidad_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  node_modules:
    driver: local

networks:
  universidad_network:
    driver: bridge
